// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PasajesAeropuerto.Data;

#nullable disable

namespace PasajesAeropuerto.Migrations
{
    [DbContext(typeof(PasajesAeropuertoContext))]
    partial class PasajesAeropuertoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PasajesAeropuerto.Entities.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Km")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Destinos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Km = 0.0,
                            Nombre = "Buenos Aires",
                            PrecioBase = 0.00m
                        },
                        new
                        {
                            Id = 2,
                            Km = 1350.5,
                            Nombre = "Bariloche",
                            PrecioBase = 45000.00m
                        },
                        new
                        {
                            Id = 3,
                            Km = 1050.2,
                            Nombre = "Mendoza",
                            PrecioBase = 32000.00m
                        },
                        new
                        {
                            Id = 4,
                            Km = 700.0,
                            Nombre = "Córdoba",
                            PrecioBase = 22000.00m
                        });
                });

            modelBuilder.Entity("PasajesAeropuerto.Entities.Equipaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PasajeroId")
                        .HasColumnType("int");

                    b.Property<int>("TipoEquipajeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PasajeroId");

                    b.HasIndex("TipoEquipajeId");

                    b.ToTable("Equipajes", t =>
                        {
                            t.HasCheckConstraint("CK_Equipaje_Cantidad", "[Cantidad] > 0");
                        });
                });

            modelBuilder.Entity("PasajesAeropuerto.Entities.Origen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Origenes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Buenos Aires"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Córdoba"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Mendoza"
                        });
                });

            modelBuilder.Entity("PasajesAeropuerto.Entities.Pasajero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ReservaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservaId");

                    b.ToTable("Pasajeros");
                });

            modelBuilder.Entity("PasajesAeropuerto.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DestinoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrigenId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCalculado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VueloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId");

                    b.HasIndex("OrigenId");

                    b.HasIndex("VueloId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("PasajesAeropuerto.Entities.TipoEquipaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Recargo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TiposEquipaje");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Equipaje de mano",
                            Recargo = 0.00m
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Valija",
                            Recargo = 8000.00m
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Equipaje adicional",
                            Recargo = 12000.00m
                        });
                });

            modelBuilder.Entity("PasajesAeropuerto.Entities.Vuelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aerolinea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsTemporadaAlta")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraLlegada")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraSalida")
                        .HasColumnType("time");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Vuelos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aerolinea = "Aerolíneas Argentinas",
                            EsTemporadaAlta = false,
                            FechaSalida = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraLlegada = new TimeSpan(0, 10, 45, 0, 0),
                            HoraSalida = new TimeSpan(0, 8, 30, 0, 0),
                            Numero = "AR1400"
                        },
                        new
                        {
                            Id = 2,
                            Aerolinea = "JetSMART",
                            EsTemporadaAlta = true,
                            FechaSalida = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraLlegada = new TimeSpan(0, 16, 30, 0, 0),
                            HoraSalida = new TimeSpan(0, 14, 15, 0, 0),
                            Numero = "WJ3420"
                        },
                        new
                        {
                            Id = 3,
                            Aerolinea = "Flybondi",
                            EsTemporadaAlta = false,
                            FechaSalida = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraLlegada = new TimeSpan(0, 20, 30, 0, 0),
                            HoraSalida = new TimeSpan(0, 19, 0, 0, 0),
                            Numero = "FB5200"
                        });
                });

            modelBuilder.Entity("PasajesAeropuerto.Entities.Equipaje", b =>
                {
                    b.HasOne("PasajesAeropuerto.Entities.Pasajero", "Pasajero")
                        .WithMany("Equipajes")
                        .HasForeignKey("PasajeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PasajesAeropuerto.Entities.TipoEquipaje", "TipoEquipaje")
                        .WithMany("Equipajes")
                        .HasForeignKey("TipoEquipajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pasajero");

                    b.Navigation("TipoEquipaje");
                });

            modelBuilder.Entity("PasajesAeropuerto.Entities.Pasajero", b =>
                {
                    b.HasOne("PasajesAeropuerto.Entities.Reserva", "Reserva")
                        .WithMany("Pasajeros")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("PasajesAeropuerto.Entities.Reserva", b =>
                {
                    b.HasOne("PasajesAeropuerto.Entities.Destino", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PasajesAeropuerto.Entities.Origen", "Origen")
                        .WithMany()
                        .HasForeignKey("OrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PasajesAeropuerto.Entities.Vuelo", "Vuelo")
                        .WithMany()
                        .HasForeignKey("VueloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destino");

                    b.Navigation("Origen");

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("PasajesAeropuerto.Entities.Pasajero", b =>
                {
                    b.Navigation("Equipajes");
                });

            modelBuilder.Entity("PasajesAeropuerto.Entities.Reserva", b =>
                {
                    b.Navigation("Pasajeros");
                });

            modelBuilder.Entity("PasajesAeropuerto.Entities.TipoEquipaje", b =>
                {
                    b.Navigation("Equipajes");
                });
#pragma warning restore 612, 618
        }
    }
}
